<?php

class PostsTableSeeder extends Seeder {

	public function run()
	{
		// Uncomment the code below to wipe clean table before populating
		// DB::table('posts')->truncate();

		$posts = [
			['post_title'=>'Why Atom Wont Replace Vim', 'post_content'=>'1976 was a good year for text editors. At MIT, Richard Stallman and Guy Steele wrote the first version of Emacs. And over at Berkeley, Bill Joy wrote vi (though it wouldn’t be called that for a few years yet).

			It’s reductionist to say that these two editors were each built around one big idea, but what the hell, let’s be reductionist. Because what stands out in 2014, looking at modern editors like Sublime Text and Atom, is how Emacs’ big idea has been thoroughly learned — and how vi’s big idea hasn’t.'],
			['post_title'=>'Reconfiguring the Databody', 'post_content'=>'I once wrote an essay on this topic. I\'m not linking it here. Basically I went on about the fact you are commonly represented digitally by a body of data generated from your online activities which is, for the purposes of machine-to-machine(M2M) communication, essentially equivalent to your physical body.'],
			['post_title'=>'The Economics of Star Trek : The Proto-Post Scarcity Economy', 'post_content'=>'I believe the federation is a proto-post scarcity society evolved from democratic capitalism. It is, essentially, European socialist capitalism vastly expanded to the point where no one has to work unless they want to.
			It is massively productive and efficient, allowing for the effective decoupling of labor and salary for the vast majority (but not all) of economic activity. The amount of welfare benefits available to all citizens is in excess of the needs of the citizens. Therefore, money is irrelevant to the lives of the citizenry, whether it exists or not. Resources are still accounted for and allocated in some manner, presumably by the amount of energy required to produce them (say Joules). And they are indeed credited to and debited from each citizen’s “account.” However, the average citizen doesn’t even notice it, though the government does, and again, it is not measured in currency units — definitely not Federation Credits. There is some level of scarcity — the Federation cannot manufacture a million starships, for example. This massive accounting is done by the Federation government in the background (witness the authority of the Federation President over planetary power supplies).
			Because the welfare benefit is so large, and social pressure is so strong against conspicuous consumption, the average citizen never pays any attention to the amounts allocated to them, because it’s perpetually more than they need. But if they go crazy and try and purchase, say, 10 planets or 100 starships, the system simply says “no.”
			Citizens have no financial need to work, as their benefits are more than enough to provide a comfortable life, and there is, clearly, universal health care and education. The Federation has clearly taken the plunge to the other side of people’s fears about European socialist capitalism: yes, some people might not work. So What? Good for them. We think most still will.
			However, if they so choose they can also get a job. Many people do so for personal enrichment, societal pressure or through a desire to promote social welfare. Are those jobs paid? I would assume that yes, those jobs are “paid,” in the sense that your energy allocation is increased in the system, though, again, your allocation is large enough that you wouldn’t even really notice it. Why do I say this? The big challenge here is how does society get someone to do the menial jobs that cannot be done in an automated manner. Why would anyone? There are really only two options: there is some small, incremental increase in your hypothetical maximum consumption, thus appealing to the subconscious in some primal way, or massive societal pressure has ennobled those jobs in a way that we don’t these days. I opt for the former since it grounds everything in market economics, albeit on a bordering-on-infinitesimal manner, and that stands to reason, since that’s how people talk in Star Trek. They talk about individual fulfillment, buying, selling, etc. No one was ever guilt-tripped into joining Starfleet, save by maybe their family.'],
			['post_title'=>'Lorem Ipsum', 'post_content'=>'When creating a new model, you pass an array of attributes to the model constructor. These attributes are then assigned to the model via mass-assignment. This is convenient; however, can be a serious security concern when blindly passing user input into a model. If user input is blindly passed into a model, the user is free to modify any and all of the models attributes. For this reason, all Eloquent models protect against mass-assignment by default.'],
			['post_title'=>'Manual Seeding Sucks', 'post_content'=>'Manta rays are large eagle rays belonging to the genus Manta. The larger species, M. birostris, reaches 7 m (23 ft 0 in) in width while the smaller, M. alfredi, reaches 5.5 m (18 ft 1 in). Both have triangular pectoral fins, horn-shaped cephalic fins and large, forward-facing mouths. They are classified among the Elasmobranchii (sharks and rays) and are placed in the eagle ray family, Myliobatidae.

			Mantas are found in temperate, subtropical and tropical waters. Both species are pelagic; M. birostris migrates across open oceans, singly or in groups, while M. alfredi tends to be resident and coastal. They are filter feeders and eat large quantities of zooplankton, which they swallow with their open mouths as they swim. Gestation lasts over a year, producing live pups. Mantas may visit cleaning stations for the removal of parasites. Like whales, they breach, for unknown reasons.

Both species are listed as vulnerable by the International Union for Conservation of Nature. Anthropogenic threats include pollution, entanglement in fishing nets, and direct harvesting for their gill rakers for use in Chinese medicine. Their slow reproductive rate exacerbates these threats. They are protected in international waters by the Convention on Migratory Species of Wild Animals, but are more vulnerable closer to shore. Areas where mantas congregate are popular with tourists. Only a few aquariums are large enough to house them. In general, these large fish are seldom seen and difficult to study.'],
			['post_title'=>'Tired Now', 'post_content'=>'According to OCHA, as of 29 July 2014 in the Gaza Strip, over 240,000 Palestinians have been displaced of which 200,400 are taking shelter in 85 UNRWA schools (over eleven percent of the Gazan population). UNRWA has exhausted its capacity to absorb displaced persons, and overcrowding in shelters risks the outbreak of epidemics. 1.2 million people have no access or very limited access to water or sanitation, 133 schools and 23 health facilities have been damaged, 4,025 housing units have been destroyed or severely damaged rendering them uninhabitable; 4,565 housing units have been damaged but are still inhabitable. 80% of Gazans receive only 2 hours of electricity per day. The destruction of Gaza’s only power plant is expected to have a further deteriorating impact on the availability of food and access to basic services.'],
			['post_title'=>'Random Text', 'post_content'=>'<p>One could not help contrasting this large force from Australia and New Zealand—a force that was to be doubled and trebled ere long—with the little force of 500 men which William Bede Dalley, Australian Orator and Patriot, sent from New South Wales to the Sudan just thirty years before. It spoke not only of the wonderful growth in population of Britain\'s Dominions of the South, but it was a living proof that the years had only served to cement the bonds of love and loyalty that bind the grand old Mother land to her Oversea Dominions. The rising in India, the intention of the Australians to proclaim their independence the moment when Britain found herself in peril—where were they? Where now was the \"disintegration\" of the British Empire which the German Emperor and his War Lords had so confidently predicted?</p>
						<p>With Cairo and the Nile safe, General Wilson was able to deal effectively with the invaders. Towards the latter end of January, Northern Sinai was overrun with them. From a couple of captured Shawishes of the 75th Turkish Regiment I learned that the staff arrangements by the German officers were excellent. Everything had been foreseen and provided for—or nearly everything. Water was available at each stage of the journey across the desert. Many boats and pontoons were dragged by oxen and camels along the caravan route from Kosseima, El Arish, and Nekl. A few six-inch guns were also transported to the Canal. To supplement the Turkish force on its south-westerly march all the pilgrims and Bedouins met with were pressed into service and rifles were given to them.</p>
						<p>It was on the morning of January 28 that the initial conflict took place at Kantara. A reconnoitring party from Bir El Dueidar attacked the British outposts but was repulsed, our losses being only one officer and one soldier killed and five Gurkhas wounded. Further south, near Suez, a nocturnal demonstration by the Turks merely served to prove the alertness of the defenders, though unfortunately two of our air scouts met with disaster. Their aeroplane came down outside our lines, and on returning on foot they were both shot dead by our own Indian patrols. The pity of it.</p>
'],
			['post_title'=>'Taking Sneezes', 'post_content'=>'					<p>I am living Egypt, living.... Your pyramids and your mosques and your old Nile can talk to me of things long past and gone, and I shall listen with interest to what they have to say, but I would rather be a living dog of an Egyptian than the dead lion of an Egyptian king—I would rather be a moving, talking native dressed in garish clothes than a Prince of the House of Rameses, sans eyes, sans ears, sans tongue, in the shrivelled brown form of a mummy.</p>
						<p>For there is something about these living ones that brings the dead to life. Sometimes when I look into their eyes I seem to see a strange, mysterious light in them—a light that never was on sea or land. It is then that I think of the things these people have seen in the forty centuries of which Napoleon spoke. I don\'t believe in magic, but I have seen strange things—things that make me remember that the magicians of Pharaoh were able to turn their rods into serpents!</p>
						<p>There came one day a very wise Egyptian—one whom I know as a Freemason—and he gave a valuable scarab, mounted in a gold ring, to Major Lynch. There was no doubt that the wise man valued it, and there is no doubt that he left an impression on Major Lynch. It is a talisman and a protection to the owner, but it has deadly powers. Nothing can harm the owner so long as he has it in his possession, and the owner can shrivel up an enemy by merely pointing at him and muttering incantations—just as the Northern Territory natives in Australia can will an enemy to die by pointing a bone at him. Major Lynch lost no time in putting the scarab to the test. There was a very troublesome native who used to bother him several times a day about things that don\'t matter, and the day after the wise Egyptian had made his presentation the major pointed at the native and muttered a powerful Australian incantation. Since then the native has not been seen.</p>'],
			['post_title'=>'Kissing Ass', 'post_content'=>'					<p>One night stands out—a gorgeous night—a carnival in honour and aid of brave little Serbia. Kipling says that "East is east and west is west, and never the twain shall meet"; but he surely has not seen a Venetian carnival in Cairo, with its intermingling of the progressive Occident and the picturesque Orient. One will always remember that. When the tourists from the West overrun the land of the Pharaohs, as they do once a year, a Venetian fête is held at Shepheard\'s—the social event of the season. Sightseers from England, idle rich from the Continent, plutocrats from America, tourists from the four quarters of the world, all meet and make merry here. This year of grace witnessed a somewhat different spectacle, it is true. It was a polyglot gathering of all nations, to be sure, but the tourist element was wanting. In the place of the tourists, however, was the \"Army of Occupation.\" Hundreds of officers, British, French, Egyptian, Australian and New Zealand, in smart uniforms, gave striking colour to the scene, which was made additionally picturesque by the vari-coloured silks and satins, scarfs and veils of the ladies. The garden was a blaze of splendour. There were the flags of the nations, there were flowers and palms and purling fountains, mirth and music, lights and laughter, and over all—confetti. All night the air was thick with confetti, like snow falling off a rainbow. Revellers flew hither and thither, flinging it everywhere. Merry maidens threw handfuls of confetti and eyesful of bold glances at the sun-tanned colonials. There was no respite until the ground was ankle-deep with confetti.</p>
						<p>But even a plague of locusts does not last for ever—and Egypt does. Egypt the wonderful! Egypt the kaleidoscopic! No, gentle reader, do not waste your sympathies on us. It was tiresome work, marching, training—training for the front, which for months never seemed to get any nearer, and some of "the boys"—those of them who were "spoiling for a fight," as the saying is—used at times to kick over the traces and paint the town vermilion; but there are compensations in Egypt for all who would seek them. What did it matter that we had no hot cross buns for Easter, no hard-boiled eggs, no ling, no salmon? We had omelettes and quail on toast, and chicken and curry and strawberries (no cream) and oranges and custard and jelly and Turkish coffee and Nile fish and pancakes and fritters and iced butter and beautiful jam and marmalade—and cigars. So we managed to get \"a snack,\" you see. And I know that I, for one, had no desire just then to swap places with any man in Australia.</p>
						<p>It was night when we got back to camp. Oh, those Egyptian nights! The winter cold has gone, and spring is in the air. The nights are fine and fair, clear and cloudless, with the moon pure silver. The reflections in the Nile are just wonderful. The huge date palms stand out sharply from a star-spangled sky that somehow has a tint of green in its blue. One thinks of the Arabian Nights. The very street scenes make one think of them. Motors glide up and down the streets with rich Syrians, Greeks, Egyptians, Italians, Frenchmen and Englishmen, going to the Continental, or to Shepheard\'s, or to private entertainments. It is a gorgeous splash of colour. They had no motor-cars that I remember in those old Arabian Nights, but the magic of the thing and the colour of it all were surely much the same. And the roads of Egypt—how beautiful they are!—clean and smooth as a billiard table. Are there any finer roads in the whole world than the Mena road and that to Heliopolis? Fifty miles an hour is easy. I sometimes shudder now when I recall the races that we used to have along those roads at night, crying "Egre! Egre!"—Faster! Faster!</p>
	']


		];
	// Uncomment the below to run the seeder
		DB::table('posts')->insert($posts);
	}

}
